<?php

/**
 * Generated by new-docs/tools/build-views.php.
 * Do not edit — change the markdown and rebuild.
 *
 * The h2 and h3 of every page, in document order, for the on-this-page rail. Built in the
 * same pass that writes the views, so the anchors here and the ids there cannot disagree.
 */

return array (
  '/' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'what-it-does',
      'text' => 'What It Does',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'build-import-extract',
      'text' => 'Build, Import, Extract',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'where-to-start',
      'text' => 'Where to Start',
    ),
  ),
  '/installation' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'composer-require',
      'text' => 'Composer Require',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'php-version',
      'text' => 'PHP Version',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'suggested-extensions',
      'text' => 'Suggested Extensions',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'quick-test',
      'text' => 'Quick Test',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/quickstart' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'a-one-page-document',
      'text' => 'A One-Page Document',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'building-a-page-from-html',
      'text' => 'Building a Page from HTML',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'adding-an-image',
      'text' => 'Adding an Image',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'importing-and-stamping-a-file',
      'text' => 'Importing and Stamping a File',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'extracting-text-back-out',
      'text' => 'Extracting Text Back Out',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/documents' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'creating-a-document',
      'text' => 'Creating a Document',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'adding-pages',
      'text' => 'Adding Pages',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'copying-reordering-and-deleting',
      'text' => 'Copying, Reordering and Deleting',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'the-current-page',
      'text' => 'The Current Page',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'inspecting-a-document',
      'text' => 'Inspecting a Document',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'compression',
      'text' => 'Compression',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'pdf-version',
      'text' => 'PDF Version',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'rendering-to-a-string',
      'text' => 'Rendering to a String',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/pages' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'creating-a-page',
      'text' => 'Creating a Page',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'page-sizes',
      'text' => 'Page Sizes',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'custom-sizes',
      'text' => 'Custom Sizes',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'the-coordinate-system',
      'text' => 'The Coordinate System',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'page-content',
      'text' => 'Page Content',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'clearing-a-page',
      'text' => 'Clearing a Page',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'page-index',
      'text' => 'Page Index',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/metadata' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'setting-document-metadata',
      'text' => 'Setting Document Metadata',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'reading-metadata-back',
      'text' => 'Reading Metadata Back',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/output' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'writing-to-a-file',
      'text' => 'Writing to a File',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'sending-to-the-browser',
      'text' => 'Sending to the Browser',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'getting-the-raw-bytes',
      'text' => 'Getting the Raw Bytes',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/text' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'adding-text-to-a-page',
      'text' => 'Adding Text to a Page',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'size-and-font',
      'text' => 'Size and Font',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'color',
      'text' => 'Color',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'outlined-text',
      'text' => 'Outlined Text',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'rotation',
      'text' => 'Rotation',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'text-parameters',
      'text' => 'Text Parameters',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'multiple-strings',
      'text' => 'Multiple Strings',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'escaping',
      'text' => 'Escaping',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/text-layout' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'character-wrapping',
      'text' => 'Character Wrapping',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'counting-wrapped-lines',
      'text' => 'Counting Wrapped Lines',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'alignment',
      'text' => 'Alignment',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'left',
      'text' => 'Left',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'right',
      'text' => 'Right',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'center',
      'text' => 'Center',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'wrapping-to-a-box',
      'text' => 'Wrapping to a Box',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/text-streams' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'creating-a-text-stream',
      'text' => 'Creating a Text Stream',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'adding-text-to-a-stream',
      'text' => 'Adding Text to a Stream',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'measuring-before-drawing',
      'text' => 'Measuring Before Drawing',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'orphans',
      'text' => 'Orphans',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'multi-column-layouts',
      'text' => 'Multi-Column Layouts',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/fonts' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'adding-a-font',
      'text' => 'Adding a Font',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'the-standard-fonts',
      'text' => 'The Standard Fonts',
    ),
    2 => 
    array (
      'level' => 3,
      'id' => 'the-benefits-of-standard-fonts',
      'text' => 'The Benefits of Standard Fonts',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'how-a-standard-font-draws-text',
      'text' => 'How a Standard Font Draws Text',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'selecting-the-current-font',
      'text' => 'Selecting the Current Font',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'measuring-a-string',
      'text' => 'Measuring a String',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'checking-what-is-available',
      'text' => 'Checking What Is Available',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/embedded-fonts' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'embedding-a-font-file',
      'text' => 'Embedding a Font File',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'supported-formats',
      'text' => 'Supported Formats',
    ),
    2 => 
    array (
      'level' => 3,
      'id' => 'truetype',
      'text' => 'TrueType',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'opentype',
      'text' => 'OpenType',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'type1',
      'text' => 'Type1',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'unicode-and-cid-fonts',
      'text' => 'Unicode and CID Fonts',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'glyph-coverage',
      'text' => 'Glyph Coverage',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'inspecting-a-parsed-font',
      'text' => 'Inspecting a Parsed Font',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/styles' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'registering-a-style',
      'text' => 'Registering a Style',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'style-color',
      'text' => 'Style Color',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'styling-an-embedded-font',
      'text' => 'Styling an Embedded Font',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/images' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'placing-an-image',
      'text' => 'Placing an Image',
    ),
    1 => 
    array (
      'level' => 3,
      'id' => 'supported-formats',
      'text' => 'Supported Formats',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'images-from-a-stream',
      'text' => 'Images from a Stream',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'resizing',
      'text' => 'Resizing',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'scaling',
      'text' => 'Scaling',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'reading-back-dimensions',
      'text' => 'Reading Back Dimensions',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'preserved-resolution',
      'text' => 'Preserved Resolution',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'a-page-built-from-an-image',
      'text' => 'A Page Built From an Image',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/paths' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'adding-a-path-to-a-page',
      'text' => 'Adding a Path to a Page',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'fill-and-stroke',
      'text' => 'Fill and Stroke',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'shapes',
      'text' => 'Shapes',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'lines',
      'text' => 'Lines',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'rectangles-and-squares',
      'text' => 'Rectangles and Squares',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'rounded-rectangles-and-squares',
      'text' => 'Rounded Rectangles and Squares',
    ),
    6 => 
    array (
      'level' => 3,
      'id' => 'polygons',
      'text' => 'Polygons',
    ),
    7 => 
    array (
      'level' => 3,
      'id' => 'ellipses-and-circles',
      'text' => 'Ellipses and Circles',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'arcs-chords-and-pies',
      'text' => 'Arcs, Chords and Pies',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'b-zier-curves',
      'text' => 'Bézier Curves',
    ),
    10 => 
    array (
      'level' => 3,
      'id' => 'cubic',
      'text' => 'Cubic',
    ),
    11 => 
    array (
      'level' => 3,
      'id' => 'quadratic',
      'text' => 'Quadratic',
    ),
    12 => 
    array (
      'level' => 2,
      'id' => 'layers',
      'text' => 'Layers',
    ),
    13 => 
    array (
      'level' => 2,
      'id' => 'path-styles',
      'text' => 'Path Styles',
    ),
    14 => 
    array (
      'level' => 3,
      'id' => 'even-odd-filling',
      'text' => 'Even-Odd Filling',
    ),
    15 => 
    array (
      'level' => 3,
      'id' => 'clipping',
      'text' => 'Clipping',
    ),
    16 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/annotations' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'linking-to-a-url',
      'text' => 'Linking to a URL',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'linking-within-the-document',
      'text' => 'Linking Within the Document',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'sizing-the-clickable-area',
      'text' => 'Sizing the Clickable Area',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'border-appearance',
      'text' => 'Border Appearance',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/forms' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'creating-a-form',
      'text' => 'Creating a Form',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'adding-a-field-to-a-page',
      'text' => 'Adding a Field to a Page',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'options-every-field-has',
      'text' => 'Options Every Field Has',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'borders-and-backgrounds',
      'text' => 'Borders and Backgrounds',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'text-fields',
      'text' => 'Text Fields',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'multiline',
      'text' => 'Multiline',
    ),
    6 => 
    array (
      'level' => 3,
      'id' => 'password',
      'text' => 'Password',
    ),
    7 => 
    array (
      'level' => 3,
      'id' => 'comb-fields',
      'text' => 'Comb Fields',
    ),
    8 => 
    array (
      'level' => 3,
      'id' => 'file-select',
      'text' => 'File Select',
    ),
    9 => 
    array (
      'level' => 3,
      'id' => 'rich-text',
      'text' => 'Rich Text',
    ),
    10 => 
    array (
      'level' => 3,
      'id' => 'spell-check-and-scrolling',
      'text' => 'Spell Check and Scrolling',
    ),
    11 => 
    array (
      'level' => 2,
      'id' => 'choice-fields',
      'text' => 'Choice Fields',
    ),
    12 => 
    array (
      'level' => 3,
      'id' => 'dropdowns',
      'text' => 'Dropdowns',
    ),
    13 => 
    array (
      'level' => 3,
      'id' => 'list-boxes',
      'text' => 'List Boxes',
    ),
    14 => 
    array (
      'level' => 3,
      'id' => 'commit-on-change',
      'text' => 'Commit on Change',
    ),
    15 => 
    array (
      'level' => 2,
      'id' => 'buttons',
      'text' => 'Buttons',
    ),
    16 => 
    array (
      'level' => 3,
      'id' => 'checked-state',
      'text' => 'Checked State',
    ),
    17 => 
    array (
      'level' => 3,
      'id' => 'radio-groups',
      'text' => 'Radio Groups',
    ),
    18 => 
    array (
      'level' => 3,
      'id' => 'push-buttons',
      'text' => 'Push Buttons',
    ),
    19 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/html' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'converting-a-string-of-html',
      'text' => 'Converting a String of HTML',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'converting-a-file',
      'text' => 'Converting a File',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'using-the-parser-directly',
      'text' => 'Using the Parser Directly',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'styling',
      'text' => 'Styling',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'inline-and-embedded-css',
      'text' => 'Inline and Embedded CSS',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'css-from-a-file',
      'text' => 'CSS From a File',
    ),
    6 => 
    array (
      'level' => 3,
      'id' => 'css-from-a-uri',
      'text' => 'CSS From a URI',
    ),
    7 => 
    array (
      'level' => 3,
      'id' => 'default-styles',
      'text' => 'Default Styles',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'page-setup',
      'text' => 'Page Setup',
    ),
    9 => 
    array (
      'level' => 3,
      'id' => 'page-size',
      'text' => 'Page Size',
    ),
    10 => 
    array (
      'level' => 3,
      'id' => 'margins',
      'text' => 'Margins',
    ),
    11 => 
    array (
      'level' => 2,
      'id' => 'controlling-flow',
      'text' => 'Controlling Flow',
    ),
    12 => 
    array (
      'level' => 2,
      'id' => 'tables',
      'text' => 'Tables',
    ),
    13 => 
    array (
      'level' => 2,
      'id' => 'form-markup',
      'text' => 'Form Markup',
    ),
    14 => 
    array (
      'level' => 3,
      'id' => 'what-each-control-becomes',
      'text' => 'What Each Control Becomes',
    ),
    15 => 
    array (
      'level' => 3,
      'id' => 'sizing-a-control',
      'text' => 'Sizing a Control',
    ),
    16 => 
    array (
      'level' => 3,
      'id' => 'styling-a-control',
      'text' => 'Styling a Control',
    ),
    17 => 
    array (
      'level' => 3,
      'id' => 'radio-groups',
      'text' => 'Radio Groups',
    ),
    18 => 
    array (
      'level' => 3,
      'id' => 'controls-outside-a-form',
      'text' => 'Controls Outside a Form',
    ),
    19 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/build/security' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'password-protecting-a-document',
      'text' => 'Password-Protecting a Document',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'restricting-what-a-reader-allows',
      'text' => 'Restricting What a Reader Allows',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'what-gets-encrypted',
      'text' => 'What Gets Encrypted',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/import/importing' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'importing-a-file',
      'text' => 'Importing a File',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'selecting-pages',
      'text' => 'Selecting Pages',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'adding-to-an-imported-document',
      'text' => 'Adding to an Imported Document',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'importing-raw-bytes',
      'text' => 'Importing Raw Bytes',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'building-a-document-from-images',
      'text' => 'Building a Document From Images',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/import/merging' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'merging-files',
      'text' => 'Merging Files',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'merging-raw-data',
      'text' => 'Merging Raw Data',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'merging-into-an-existing-document',
      'text' => 'Merging Into an Existing Document',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/import/modifying' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'adding-content-to-an-imported-page',
      'text' => 'Adding Content to an Imported Page',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'working-with-a-specific-page',
      'text' => 'Working With a Specific Page',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'replacing-a-page-s-content',
      'text' => 'Replacing a Page\'s Content',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'fonts-on-imported-pages',
      'text' => 'Fonts on Imported Pages',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/import/encrypted' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'opening-with-a-password',
      'text' => 'Opening With a Password',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'reading-and-classifying',
      'text' => 'Reading and Classifying',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'merging-encrypted-sources',
      'text' => 'Merging Encrypted Sources',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'when-the-password-is-missing-or-wrong',
      'text' => 'When the Password Is Missing or Wrong',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'what-cannot-be-opened',
      'text' => 'What Cannot Be Opened',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/extract/text' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'extracting-from-a-file',
      'text' => 'Extracting From a File',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'extracting-from-raw-bytes',
      'text' => 'Extracting From Raw Bytes',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'selecting-pages',
      'text' => 'Selecting Pages',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'limiting-how-much-is-walked',
      'text' => 'Limiting How Much Is Walked',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'how-pages-are-separated',
      'text' => 'How Pages Are Separated',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'embedded-and-cid-fonts',
      'text' => 'Embedded and CID Fonts',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/extract/image-only' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'asking-about-a-whole-document',
      'text' => 'Asking About a Whole Document',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'asking-page-by-page',
      'text' => 'Asking Page by Page',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'the-raw-data-forms',
      'text' => 'The Raw-Data Forms',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'page-selection-and-limits',
      'text' => 'Page Selection and Limits',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'routing-a-scanned-document-to-ocr',
      'text' => 'Routing a Scanned Document to OCR',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/extract/images' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'extracting-every-page',
      'text' => 'Extracting Every Page',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'formats-and-resolution',
      'text' => 'Formats and Resolution',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'naming-the-output-files',
      'text' => 'Naming the Output Files',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'selecting-pages',
      'text' => 'Selecting Pages',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'extracting-for-ocr',
      'text' => 'Extracting for OCR',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'errors',
      'text' => 'Errors',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
);
