<?php

/**
 * Generated by new-docs/tools/generate-routes.php from new-docs/sitemap.php.
 * Do not edit — change the sitemap and regenerate.
 *
 * 'routes' is one static GET route per page. 'pages' is the index the controller reads
 * for a page's title, section, components and prev/next neighbours, and the nav renders
 * for the section tree.
 */

return [
    'routes' => [
        '[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/installation[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/quickstart[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/documents[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/pages[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/metadata[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/output[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/text[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/text-layout[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/text-streams[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/fonts[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/embedded-fonts[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/styles[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/images[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/paths[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/annotations[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/forms[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/html[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/build/security[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/import/importing[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/import/merging[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/import/modifying[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/import/encrypted[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/extract/text[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/extract/image-only[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/extract/images[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
    ],

    'pages' => [
        '/' => [
            'title' => 'Overview',
            'description' => 'A PHP library for building, importing and reading PDF documents from one component.',
            'section' => 'Introduction',
            'order' => 1,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/index.phtml',
            'prev' => NULL,
            'next' => '/installation',
        ],
        '/installation' => [
            'title' => 'Installation',
            'description' => 'Installing Pop PDF with Composer and confirming the install with a one-file smoke test.',
            'section' => 'Introduction',
            'order' => 2,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/installation.phtml',
            'prev' => '/',
            'next' => '/quickstart',
        ],
        '/quickstart' => [
            'title' => 'Quickstart',
            'description' => 'Five short, self-contained scripts covering text, HTML, images, importing a file and extracting text back out.',
            'section' => 'Introduction',
            'order' => 3,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/quickstart.phtml',
            'prev' => '/installation',
            'next' => '/build/documents',
        ],
        '/build/documents' => [
            'title' => 'Creating Documents',
            'description' => 'Building a Document from pages, copying and reordering them, and reading back what it holds.',
            'section' => 'Build',
            'order' => 1,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/documents.phtml',
            'prev' => '/quickstart',
            'next' => '/build/pages',
        ],
        '/build/pages' => [
            'title' => 'Pages & Coordinates',
            'description' => 'Every named page size, custom dimensions, the origin a page measures its coordinates from, and what a page holds.',
            'section' => 'Build',
            'order' => 2,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/pages.phtml',
            'prev' => '/build/documents',
            'next' => '/build/metadata',
        ],
        '/build/metadata' => [
            'title' => 'Metadata',
            'description' => 'The document info object\'s seven fields, and reading them back out of a compiled file.',
            'section' => 'Build',
            'order' => 3,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/metadata.phtml',
            'prev' => '/build/pages',
            'next' => '/build/output',
        ],
        '/build/output' => [
            'title' => 'Saving & Output',
            'description' => 'Writing a compiled document to disk, streaming it to a browser and getting its raw bytes in memory.',
            'section' => 'Build',
            'order' => 4,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/output.phtml',
            'prev' => '/build/metadata',
            'next' => '/build/text',
        ],
        '/build/text' => [
            'title' => 'Adding Text',
            'description' => 'Placing single strings on a page — size, color, an outline, rotation, multiple runs and escaping.',
            'section' => 'Build',
            'order' => 5,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/text.phtml',
            'prev' => '/build/output',
            'next' => '/build/text-layout',
        ],
        '/build/text-layout' => [
            'title' => 'Text Layout & Wrapping',
            'description' => 'Character wrapping, leading and sizing a block before it draws, plus left, right and center alignment and wrapping a paragraph around a box for exact placement.',
            'section' => 'Build',
            'order' => 6,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/text-layout.phtml',
            'prev' => '/build/text',
            'next' => '/build/text-streams',
        ],
        '/build/text-streams' => [
            'title' => 'Text Streams',
            'description' => 'Flowing a long run of text across a box, measuring it before it draws, and carrying the overflow onto a second page.',
            'section' => 'Build',
            'order' => 7,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/text-streams.phtml',
            'prev' => '/build/text-layout',
            'next' => '/build/fonts',
        ],
        '/build/fonts' => [
            'title' => 'Fonts',
            'description' => 'Registering standard PDF fonts, how they draw text, measuring strings, and checking what a document has available.',
            'section' => 'Build',
            'order' => 8,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/fonts.phtml',
            'prev' => '/build/text-streams',
            'next' => '/build/embedded-fonts',
        ],
        '/build/embedded-fonts' => [
            'title' => 'Embedding Fonts',
            'description' => 'Loading TrueType, OpenType and Type1 font files into a document, with Unicode text and glyph coverage checks.',
            'section' => 'Build',
            'order' => 9,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/embedded-fonts.phtml',
            'prev' => '/build/fonts',
            'next' => '/build/styles',
        ],
        '/build/styles' => [
            'title' => 'Styles',
            'description' => 'Binding a font, a size and a color to a name the document keeps, so addText() draws with all three at once.',
            'section' => 'Build',
            'order' => 10,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/styles.phtml',
            'prev' => '/build/embedded-fonts',
            'next' => '/build/images',
        ],
        '/build/images' => [
            'title' => 'Images',
            'description' => 'Placing JPEG, PNG and GIF images on a page, resizing and scaling them, and building a page directly from one.',
            'section' => 'Build',
            'order' => 11,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/images.phtml',
            'prev' => '/build/styles',
            'next' => '/build/paths',
        ],
        '/build/paths' => [
            'title' => 'Drawing & Paths',
            'description' => 'Lines, rectangles, polygons, ellipses, arcs and Bézier curves, with fill, stroke, layers, clipping and path styles.',
            'section' => 'Build',
            'order' => 12,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/paths.phtml',
            'prev' => '/build/images',
            'next' => '/build/annotations',
        ],
        '/build/annotations' => [
            'title' => 'Links & Annotations',
            'description' => 'Clickable URL links and in-document links, with border, radius and dash styling.',
            'section' => 'Build',
            'order' => 13,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/annotations.phtml',
            'prev' => '/build/paths',
            'next' => '/build/forms',
        ],
        '/build/forms' => [
            'title' => 'Forms & Fields',
            'description' => 'Named forms, text fields, dropdowns, list boxes, checkboxes and radio groups, and the flag each setter writes.',
            'section' => 'Build',
            'order' => 14,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/forms.phtml',
            'prev' => '/build/annotations',
            'next' => '/build/html',
        ],
        '/build/html' => [
            'title' => 'HTML to PDF',
            'description' => 'Convert an HTML string or file into a PDF document, with CSS from a string, a file or a URI.',
            'section' => 'Build',
            'order' => 15,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/html.phtml',
            'prev' => '/build/forms',
            'next' => '/build/security',
        ],
        '/build/security' => [
            'title' => 'Encryption & Permissions',
            'description' => 'Password-protecting a document with AES encryption, and restricting what a reader lets someone do once it is open.',
            'section' => 'Build',
            'order' => 16,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/build/security.phtml',
            'prev' => '/build/html',
            'next' => '/import/importing',
        ],
        '/import/importing' => [
            'title' => 'Importing',
            'description' => 'Reading an existing PDF file or raw PDF bytes back in as a Document, with page selection, and building a document from a set of images.',
            'section' => 'Import',
            'order' => 1,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/import/importing.phtml',
            'prev' => '/build/security',
            'next' => '/import/merging',
        ],
        '/import/merging' => [
            'title' => 'Merging',
            'description' => 'Combining several existing PDF files, or raw PDF byte streams, into one Document, with control over page order and merging into a document you already built.',
            'section' => 'Import',
            'order' => 2,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/import/merging.phtml',
            'prev' => '/import/importing',
            'next' => '/import/modifying',
        ],
        '/import/modifying' => [
            'title' => 'Modifying Imported Pages',
            'description' => 'Adding text and other content to a page that came from an import or merge, working with a specific imported page, replacing what a page holds, and registering fonts alongside imported ones.',
            'section' => 'Import',
            'order' => 3,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/import/modifying.phtml',
            'prev' => '/import/merging',
            'next' => '/import/encrypted',
        ],
        '/import/encrypted' => [
            'title' => 'Opening Encrypted PDFs',
            'description' => 'Supplying a password to import, extract from, classify or merge a password-protected PDF, and what happens when the password is missing or wrong.',
            'section' => 'Import',
            'order' => 4,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/import/encrypted.phtml',
            'prev' => '/import/modifying',
            'next' => '/extract/text',
        ],
        '/extract/text' => [
            'title' => 'Extracting Text',
            'description' => 'Pulling the text layer back out of an existing PDF — page selection, page limits, how pages join, and native decoding of embedded and CID fonts.',
            'section' => 'Extract',
            'order' => 1,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/extract/text.phtml',
            'prev' => '/import/encrypted',
            'next' => '/extract/image-only',
        ],
        '/extract/image-only' => [
            'title' => 'Image-Only Pages',
            'description' => 'Detecting whether a PDF\'s pages are scanned images rather than real text, whole-document and page by page, ahead of routing them to OCR.',
            'section' => 'Extract',
            'order' => 2,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/extract/image-only.phtml',
            'prev' => '/extract/text',
            'next' => '/extract/images',
        ],
        '/extract/images' => [
            'title' => 'Pages as Images',
            'description' => 'Rasterizing the pages of an existing PDF to standalone JPEG, PNG, WebP or TIFF files, with control over format, resolution, filenames and which pages are written.',
            'section' => 'Extract',
            'order' => 3,
            'components' => [
                'pop-pdf',
            ],
            'parent' => NULL,
            'view' => 'docs/extract/images.phtml',
            'prev' => '/extract/image-only',
            'next' => NULL,
        ],
    ],
];
